import { Suspense } from "react";
import { Footer } from "./components/footer";
import { Navbar } from "./components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import CartContextProvider from "../hooks/useCartContext";

const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <CartContextProvider>
          <ToastContainer />
          <Suspense fallback="Loading header...">
            <Navbar />
          </Suspense>
          {children}
          <Suspense fallback="Loading footer...">
            <Footer />
          </Suspense>
        </CartContextProvider>
      </body>
    </html>
  );
}
