import { Navbar } from "./components/navbar";
import { Footer } from "./components/footer";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import CartContextProvider from "./hooks/useCartHook";

const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <CartContextProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <div className="grid grid-cols-5">
              <nav className="col-span-1">Side nav</nav>
              <main className="col-span-4">{children}</main>
            </div>

            <Footer />
          </div>
        </CartContextProvider>
      </body>
    </html>
  );
}
